### ISSUE TITLE
Correct automatic repo name.

### ISSUE THREAD

**Issue by AreYouLoco** [AndroidDumps/blackview_blackview_dump#1]
This repo name is wrong should be:
blackview_bv9600pro_dump
instead of
blackview_blackview_dump.

**Comment by AreYouLoco** [comment]
Here is some clear visual explanation:
https://github.com/AndroidDumps?q=blackview

**Comment by AreYouLoco** [comment]
I know it's automatic and script is generating that thing.

But could be good to fix that naming before some people might relate to that repository and then the name shouldn't be changed any more.

**Comment by ShivamKumarJha** [comment]
https://github.com/AndroidDumps/blackview_blackview_dump/blob/full_k71v1_64_bsp-user-9-PPR1.180610.011-eng.releas.20190530.193148-release-keys/system/system/build.prop#L26

retard props

**Comment by AreYouLoco** [comment]
Well. Closed cool. But still not fixed:(
Humans do better props by hand it seems and it takes like 5 seconds in total...

**Comment by ShivamKumarJha** [comment]
We aren't going to fix every wrong repo name manually. Feel free to fix the naming in script
